---
- name: Another Playbook example
  hosts: ~^arista
  gather_facts: no

  tasks: 
  - name: Precheck
    block: 
       - name: import precheck role
         import_role:
           name: alta3.example

    rescue:
      - name: precheck - FAILED
        fail:
          msg: EXITING PLAYBOOK. PRECHECK FAIL.

      
