---
- name: How to display values to the screen
  hosts: localhost
  gather_facts: no

  vars:
    vendorip: "192.168.30.10"

  tasks:

   - name: learning to debug
     debug: 
      msg: The value of the variable vendorip is {{ vendorip }}

   - name: just dump a var
     debug:
       var: vendorip
           
